const Order = require("../models/Order");
const Medicine = require("../models/Medicine");

// @route POST /api/orders
const placeOrder = async (req, res) => {
  try {
    const { medicines, deliveryAddress } = req.body; // medicines: [{medicineId, name, quantity}]
    const order = await Order.create({
      userId: req.user.id,
      medicines,
      deliveryAddress,
    });
    res.status(201).json(order);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @route GET /api/orders
const getMyOrders = async (req, res) => {
  try {
    const orders = await Order.find({ userId: req.user.id }).sort({ createdAt: -1 });
    res.json(orders);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @route PUT /api/orders/:id/status  (admin only)
const updateOrderStatus = async (req, res) => {
  try {
    const { status } = req.body;
    const order = await Order.findByIdAndUpdate(req.params.id, { status }, { new: true });
    if (!order) return res.status(404).json({ message: "Order not found" });
    res.json(order);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @route GET /api/orders/all (admin only)
const getAllOrders = async (req, res) => {
  try {
    const orders = await Order.find().populate("userId", "name email address");
    res.json(orders);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Called internally by cron job (see utils/reminderScheduler.js)
// Checks all medicines and auto-creates an order if stock is low
const checkAndAutoReorder = async () => {
  try {
    const lowStockMedicines = await Medicine.find({
      active: true,
      $expr: { $lte: ["$stockCount", "$refillThreshold"] },
    }).populate("userId", "address");

    for (const med of lowStockMedicines) {
      await Order.create({
        userId: med.userId._id,
        medicines: [{ medicineId: med._id, name: med.name, quantity: med.durationDays }],
        deliveryAddress: med.userId.address || "Default address",
        autoGenerated: true,
      });
      console.log(`Auto-reorder created for ${med.name} (user: ${med.userId._id})`);
    }
  } catch (error) {
    console.error("Auto-reorder check failed:", error.message);
  }
};

module.exports = {
  placeOrder,
  getMyOrders,
  updateOrderStatus,
  getAllOrders,
  checkAndAutoReorder,
};
