import mongoose from "mongoose";

const orderSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    medicines: [
      {
        medicineId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Medicine",
        },
        name: {
          type: String,
        },
        quantity: {
          type: Number,
        },
      },
    ],
    status: {
      type: String,
      enum: [
        "placed",
        "packed",
        "out_for_delivery",
        "delivered",
        "cancelled",
      ],
      default: "placed",
    },
    autoGenerated: {
      type: Boolean,
      default: false, // true if triggered by low stock
    },
    deliveryAddress: {
      type: String,
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model("Order", orderSchema);